# see https://docs.docker.com/compose/extends/
version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: opencounter-slim-codenv-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=development_db
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker

  webserver:
    image: phpdockerio/nginx:latest
    container_name: opencounter-slim-codenv-webserver
    hostname: opencounter-slim-codenv-webserver
    volumes:
        - ./app:/var/www/opencounter-slim-codenv
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"

  php:
    build:
      context: ./php-fpm/
    image: acolono/php7-fpm:latest
    container_name: opencounter-slim-codenv-php-fpm
    hostname: opencounter-slim-codenv-php-fpm
    volumes:
      - ./app:/var/www/opencounter-slim-codenv
  #    - ..:/var/www/opencounter-slim-codenv
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini